packageExtensions:
  "@deck.gl/geo-layers@8.x":
    dependencies:
      "@deck.gl/mesh-layers": 8.x
  "@deck.gl/layers@6.x":
    dependencies:
      luma.gl: 6.x
  "@deck.gl/layers@7.x":
    dependencies:
      "@luma.gl/core": 7.x
  "@deck.gl/layers@8.x":
    dependencies:
      "@deck.gl/core": 8.x
      "@luma.gl/core": 8.x
      math.gl: "*"
  "@deck.gl/mesh-layers@8.x":
    dependencies:
      "@deck.gl/core": 8.x
  "@deck.gl/react@8.x":
    dependencies:
      "@deck.gl/core": 8.x
  "@deck.gl/test-utils@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@luma.gl/core@6.x":
    dependencies:
      "@luma.gl/gltools": 6.x
  "@luma.gl/core@8.x":
    dependencies:
      "@luma.gl/gltools": 8.3.1
  "@nebula.gl/layers@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@nebula.gl/layers@^0.11.2":
    dependencies:
      "@deck.gl/core": 6.x
      "@deck.gl/layers": 6.x
      deck.gl: 6.x
      luma.gl: 6.x
  "@streetscape.gl/core@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
      styletron-react: "*"
  "@streetscape.gl/layers@*":
    dependencies:
      "@deck.gl/core": 8.x
      "@deck.gl/layers": 8.x
  "@streetscape.gl/monochrome@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
      styletron-react: "*"
  deck.gl@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
  nebula.gl-react@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
  nebula.gl-react@0.10.5:
    peerDependencies:
      nebula.gl: "*"
  nebula.gl@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
  nebula.gl@^0.10.5:
    dependencies:
      "@deck.gl/core": 6.x
      "@deck.gl/layers": 6.x
      deck.gl: 6.x
  nebula.gl@^0.11.2:
    dependencies:
      "@deck.gl/core": 6.x
      "@deck.gl/layers": 6.x
      deck.gl: 6.x
      luma.gl: 6.x

pnpMode: loose

yarnPath: .yarn/releases/yarn-sources.cjs
